### ISSUE TITLE
// instead int(val)

### ISSUE THREAD

**Issue by danyalutsevich** [ArtDoctor/lorentz_attractor#1]
t = np.linspace(0.0, t_sim, int(t_sim / dt))

how about this

t = np.linspace(0.0,t_sim,t_sim//dt)

**Comment by danyalutsevich** [comment]
it works the same but looks better

**Comment by ArtDoctor** [comment]
I agree, thank you. Forgot about floor division. Will add in next commit

**Comment by ArtDoctor** [comment]
Actually, I just noticed, dt and t_sim are floats, so float division won't be a good solution in this case.
